name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    env:
      PYTHONUTF8: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install deps (runtime + dev)
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt ( pip install -r requirements.txt )
          if exist requirements-dev.txt ( pip install -r requirements-dev.txt )

      - name: Prepare .env
        run: |
          echo FMP_API_KEY=${{ secrets.FMP_API_KEY }}>> .env
          echo FRED_API_KEY=${{ secrets.FRED_API_KEY }}>> .env
          echo ALIGN_CALENDAR_UNION_FFILL=1>> .env

      - name: Run tests (offline/schema only)
        run: pytest -q -k "offline or schema"
