name: VolAI Cron (call /scheduler/run)

on:
  workflow_dispatch: {}      # 手動実行ボタン
  schedule:
    - cron: "*/5 * * * *"    # 5分おき（UTC）

jobs:
  call-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Call /login and then /scheduler/run
        env:
          API_BASE: ${{ secrets.API_BASE }}
          API_EMAIL: ${{ secrets.API_EMAIL }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
        run: |
          set -e
          echo "API_BASE=$API_BASE"
          echo "Getting token..."
          TOKEN=$(curl -s -X POST "$API_BASE/login" \
            -H "Content-Type: application/json" \
            -d "{\"email\":\"$API_EMAIL\",\"password\":\"$API_PASSWORD\"}" | jq -r '.access_token')

          if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
            echo "Login failed"; exit 1
          fi

          echo "Trigger /scheduler/run"
          curl -s -f -X POST "$API_BASE/scheduler/run" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json"

          echo "Done"
