name: VolAI Cron (call /ops/jobs/run)

on:
  schedule:
    # 5分おき（UTC）— 好きな間隔に変えてOK
    - cron: "*/5 * * * *"
  workflow_dispatch: {}  # 手動実行ボタンも出す

jobs:
  run-news-sentiment:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Login and run news_sentiment
        env:
          BASE: ${{ secrets.VOLAI_BASE }}
          EMAIL: ${{ secrets.VOLAI_EMAIL }}
          PASSWORD: ${{ secrets.VOLAI_PASSWORD }}
        run: |
          set -euo pipefail
          echo "Login to $BASE ..."
          TOK=$(curl -sS -X POST "$BASE/login" \
            -H "Content-Type: application/json" \
            -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}" \
            | jq -r .access_token)
          if [ -z "$TOK" ] || [ "$TOK" = "null" ]; then
            echo "Login failed"; exit 1
          fi
          echo "Token acquired."

          echo "Run job: news_sentiment (window_hours=6)"
          curl -sSf -X POST "$BASE/ops/jobs/run?name=news_sentiment&window_hours=6" \
            -H "Authorization: Bearer $TOK" \
            -H "Content-Type: application/json" \
            | tee /dev/stderr
