on:
  schedule:
    - cron: "0 0 * * *"   # 00:00 UTC = 20:00 EDT（夏時間）
    - cron: "0 1 * * *"   # 01:00 UTC = 20:00 EST（冬時間）

jobs:
  run-news-sentiment:
    runs-on: ubuntu-latest
    steps:
      - name: Run only at 20:00 Toronto (DST-safe guard)
        run: |
          if [ "$(TZ=America/Toronto date +%H)" != "20" ]; then
            echo "Not 20:00 in Toronto. Skip."; exit 0; fi

      # ←この下は、今使っている Health→Login→/ops/jobs/run の“堅牢版”をそのまま残せばOK
      - name: Run news_sentiment job (24h window)
        env:
          BASE: ${{ secrets.VOLAI_BASE }}
          EMAIL: ${{ secrets.VOLAI_EMAIL }}
          PASSWORD: ${{ secrets.VOLAI_PASSWORD }}
        run: |
          set -euo pipefail
          BASE="${BASE%/}"
          # Health
          code=$(curl -sS -m 10 -o /dev/null -w '%{http_code}' "$BASE/health" || true)
          [ "$code" = "200" ] || { echo "health=$code"; exit 1; }
          # Login
          TOK=$(curl -sS -X POST "$BASE/login" -H "Content-Type: application/json" \
                -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}" | jq -r .access_token)
          [ -n "$TOK" ] && [ "$TOK" != "null" ] || { echo "login failed"; exit 1; }
          # Run（1日分を集計）
          curl -sS -f -X POST "$BASE/ops/jobs/run?name=news_sentiment&window_hours=24" \
               -H "Authorization: Bearer $TOK" -H "Content-Type: application/json" \
               | tee /dev/stderr
          echo "Done"
