name: VolAI Cron (call /ops/jobs/run)

on:
  # 手動実行ボタン
  workflow_dispatch: {}

  # 毎日トロント 20:00 に実行（DST対応：夏/冬で2本）
  schedule:
    - cron: "0 0 * * *"   # 00:00 UTC = 20:00 EDT（夏時間）
    - cron: "0 1 * * *"   # 01:00 UTC = 20:00 EST（冬時間）

jobs:
  run-news-sentiment:
    # mainブランチだけで動かす（おすすめ）
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    # 走り過ぎ防止（同じジョブが重なったら新しい方は待機）
    concurrency:
      group: volai-cron
      cancel-in-progress: false

    timeout-minutes: 10

    steps:
      - name: Show times (UTC & Toronto)
        run: |
          date -u +"UTC     %Y-%m-%d %H:%M:%S"
          TZ=America/Toronto date +"Toronto %Y-%m-%d %H:%M:%S %Z"

      - name: Run only at 20:00 Toronto (DST-safe guard)
        run: |
          if [ "$(TZ=America/Toronto date +%H)" != "20" ]; then
            echo "Not 20:00 in Toronto. Skip."; exit 0; fi

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run news_sentiment job via /ops/jobs/run  (robust w/ retry)
        env:
          BASE: ${{ secrets.VOLAI_BASE }}
          EMAIL: ${{ secrets.VOLAI_EMAIL }}
          PASSWORD: ${{ secrets.VOLAI_PASSWORD }}
        run: |
          set -euo pipefail

          # 末尾スラ除去
          BASE="${BASE%/}"
          echo "BASE=$BASE"

          echo "Health check with retry..."
          ok=0
          for i in {1..10}; do
            code=$(curl -sS -m 10 -L -o /dev/null -w '%{http_code}' "$BASE/health" || true)
            echo " try #$i: /health => $code"
            if [ "$code" = "200" ]; then ok=1; break; fi
            sleep $((i*2))
          done
          if [ "$ok" -ne 1 ]; then
            echo " /health did not reach 200. Last verbose attempt:"
            curl -v "$BASE/health" || true
            exit 1
          fi

          echo "Login with retry..."
          TOK=""
          for i in {1..5}; do
            RESP=$(curl -sS -m 20 -L -X POST "$BASE/login" \
              -H "Content-Type: application/json" \
              -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}" \
              --retry 5 --retry-delay 2 --retry-all-errors || true)
            TOK=$(echo "$RESP" | jq -r '.access_token')
            if [ -n "${TOK:-}" ] && [ "$TOK" != "null" ]; then
              echo " Token acquired."
              break
            fi
            echo " login retry #$i failed; sleeping..."
            sleep 3
          done
          if [ -z "${TOK:-}" ] || [ "$TOK" = "null" ]; then
            echo "Login failed (no token)"; exit 1
          fi

          echo "Run job (retry on network errors)..."
          curl -sS -f -X POST "$BASE/ops/jobs/run?name=news_sentiment&window_hours=24" \
            -H "Authorization: Bearer $TOK" \
            -H "Content-Type: application/json" \
            --retry 5 --retry-delay 2 --retry-all-errors \
            | tee /dev/stderr

          echo "Done"
